### ISSUE TITLE
Rename from ng-patterns to ng-patternlab?

### ISSUE THREAD

**Issue by jeffreynolte** [moxie-lean/ng-patternlab#25]
I realize angular has ng-pattern. It may be a good idea to rename this to ng-patternlab

**Comment by chrisweight** [comment]
It might be a good idea to consider renaming anything with ng-\* in front, as that can be confused with core elements of Angular itsellf, maybe stick with the ln-\* prefix?

ln-patternlab?

**Comment by jeffreynolte** [comment]
Thanks @chrisweight

:+1: on ln convention.

**Comment by adamf321** [comment]
That doesn't work... because we have both wordpress and angular libs under the same github user. We need a way to tell them apart, so using ln- won't work.

**Comment by adamf321** [comment]
Discussed with Andre - we'll update to ng-patternlab for now. I'm open to suggestions on a better naming convention...

**Comment by andybar2** [comment]
Done
