### ISSUE TITLE
Format code

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/ng-patternlab#27]
The code should looks like and follow the lint rules at the moment is having different conventions inside. The main reasons of the PR are to aim consistency looks like is not the current case at the moment. If we are not doing that during PR there is no so much reason to have a PR system.

Please make sure to update the format of the code to follow the lint rules so we all follow the same style at coding, since the code should look like if was written by a single person. 

And if someone wants to discuss a certain rule please ask on the chat room so we can discuss around that.

Thanks.

**Comment by adamf321** [comment]
Thanks Cris, @chrisweight and @andybar2 are aware of this. They are going to fix it.

**Comment by adamf321** [comment]
But we should automate this so the code style is checked by the Lint scripts, not manually in the PR (see https://github.com/moxie-leean/ng-web-app/issues/48).

The PR should be to review structure and other bigger concepts like that.

**Comment by mitogh** [comment]
Yes agreed, all of styles rules should be checked by the lint.

**Comment by chrisweight** [comment]
It might worth using pre-commit hooks to enforce linting, depending on how strict you want to be - as that'll reduce build-failures and excess logging.

**Comment by mitogh** [comment]
It might be a good solution but I think this might be a more personal approach in order to remember to run the linter.

The way we do in other projects is that any PR that does not pass the lint is not able to be merged on develop or master so in this way we force contributors to make sure all changes follow the rules created by the lint.
