### ISSUE TITLE
There is a debug line on production

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/ng-patternlab#36]
Ref: https://github.com/moxie-leean/ng-patternlab/blob/efc77d218a148971a35aac4bfb91d2ce13acd287/lib/organisms/gravity-form/gravity-form.controller.js#L29

**Comment by chrisweight** [comment]
This has been removed on the develop branch, so should be resolved on the next release to master :)

**Comment by mitogh** [comment]
Thank you.
