### ISSUE TITLE
Add ng-classes to gravityForms component

### ISSUE THREAD

**Issue by camilodelvasto** [moxie-lean/ng-patternlab#42]
The rendered form should have ng-classes like ng-dirty/ng-valid/etc so that validation while tyiping can be used. It should cover:
- invalid field
- touched field
- invalid form (so that we can apply cursor:disabled to submit button)

**Comment by adamf321** [comment]
Doesn't angular add these automatically?

**Comment by camilodelvasto** [comment]
That's what I'm wondering....
Some classes are there, though not all them, but they don't change as user types (always assigning ng-pristine)

**Comment by chrisweight** [comment]
https://github.com/moxie-leean/ng-patternlab/pull/44 
addresses this :)
