### ISSUE TITLE
Base atoms

### ISSUE THREAD

**Issue by adamf321** [moxie-lean/ng-patternlab#5]
Add all commonly used atoms - eg h1, h2, a, button, etc.
I think we should use the name of the HTML tag to make it easier to remember. Also we should group by similar types. Eg:

```
atoms/
  headings/
    h1/
      h1.directive.js [directive is called as <ln-a-h1 ...>]
  h2/
      h2.directive.js [directive is called as <ln-a-h2 ...>]
  links/
    a/
      a.directive.js [directive is called as <ln-a-a ...>]
    button/
      button.directive.js [directive is called as <ln-a-button ...>]
```

**Comment by andybar2** [comment]
This is ready for most common html tags: https://github.com/moxie-leean/ng-patternlab/tree/master/lib/atoms
