### ISSUE TITLE
Admin bar component is doing multiple HTTP requests

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/ng-patternlab#83]
**Steps to reproduce and a minimal demo of the problem**

Open the Chrome Inspector tool on the, **Network** tab.

**Current behavior**

The admin bar component is doing 3 requests.

**Expected/desired behavior**

Admin bar should do only one `XHR` request since the other 2 are not required

**Other information**

<img width="815" alt="screen shot 2016-06-14 at 12 15 55 pm" src="https://cloud.githubusercontent.com/assets/3921289/16052409/c63880b0-3229-11e6-81b7-1a0b7e55617c.png">

**Comment by adamf321** [comment]
this will fix it: https://github.com/moxie-lean/ng-web-app/issues/63  (at least patch it up, there may be an actual issue causing it to make 3 calls)

**Comment by mitogh** [comment]
I think the problem is a logic issue that creates 3 calls to the same APi. The cache willl still do 3 requests one to the API and 2 to the cache. So the main thing I guess is debug the component in order to just do one requests. Since this is happening on every page you visit so even if we use the cache as I mentioned before I think we are still experience the same problem.

**Comment by adamf321** [comment]
Yes, agreed there's an issue. The cache would mask it, but not fix it.
